---
title: "Index"
author: "Fikir Worku Edossa"
date: "8/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r results='hide', warning=FALSE, message=FALSE}
NeededPackages <- c("leaflet", "dplyr", "coronavirus","scales", "leaftime")
lapply(NeededPackages, require, character.only = TRUE)
```

## Data 

```{r warning=FALSE}
#coronavirus::update_dataset()

covid <- coronavirus::coronavirus


covidAfrica <- covid %>% 
        filter(-34.5115 < lat & lat <= 33.886917) %>% 
        filter(-17.3113 < long & long < 51.2752) %>% 
        mutate(lnglat = long + lat) %>% 
        filter (lnglat <= 58.623051) %>% 
        group_by(country, type) %>% 
        summarise(date = date, cases = cases, totalCases = cumsum(cases), lng = max(long), lat = max(lat)) %>% 
        filter(totalCases > 0) %>% 
        ungroup()

covidAfricaConfirmed <- covidAfrica[covidAfrica$type == "confirmed",]
covidAfricaDeath <- covidAfrica[covidAfrica$type == "death",]
covidAfricaRecovered <- covidAfrica[covidAfrica$type == "recovered",]
 
```


## Total Corona Cases in Africa until ```r paste(max(covidAfricaConfirmed$date))```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

covidAfricaConfirmed %>% 
        leaflet() %>% 
        addTiles() %>% 
        addCircleMarkers(weight = 5, radius = sqrt(covidAfricaConfirmed$totalCases)*0.05,
                         popup = paste(covidAfricaConfirmed$country, ": ", comma_format(accuracy = 1)(covidAfricaConfirmed$totalCases))) 
```

## Total Corona Death in Africa until ```r paste(max(covidAfricaDeath$date))```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

covidAfricaDeath %>% 
        leaflet() %>% 
        addTiles() %>% 
        addCircleMarkers(color = "red",weight = 5, radius = sqrt(covidAfricaDeath$totalCases)*0.01,
                         popup = paste(covidAfricaDeath$country, ": ", comma_format(accuracy = 1)(covidAfricaDeath$totalCases)))
```

